-- ==============================================================================
-- MANGANG FINANCE - USER AUTH (INTEGER AUTO-INCREMENT ID & SEQUENTIAL CUSTOMER ID)
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard)
-- ==============================================================================

-- 1. Drop existing table if recreating (Warning: clears test user_auth table)
DROP TABLE IF EXISTS public.user_auth CASCADE;

-- 2. Create user_auth table with INTEGER AUTO-INCREMENT (BIGINT IDENTITY 1, 2, 3...)
CREATE TABLE public.user_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile_no TEXT NOT NULL,
    name TEXT NOT NULL,
    pin TEXT NOT NULL,
    user_type TEXT NOT NULL, -- admin, manager, ro, loanee
    customer_id TEXT,        -- ADM-01, ADM-02, MGR-01, MGR-02, etc.
    ro_name TEXT,
    account_name TEXT,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Composite Unique Constraint:
-- Allows same mobile number for DIFFERENT user roles (e.g., 1 Admin + 1 Manager on same phone),
-- while preventing duplicate rows for the SAME phone and SAME role.
ALTER TABLE public.user_auth 
ADD CONSTRAINT user_auth_mobile_user_type_key UNIQUE (mobile_no, user_type);

-- 4. Trigger Function: Auto-generate sequential customer_id (ADM-01, MGR-01, RO-01)
CREATE OR REPLACE FUNCTION public.set_user_auth_customer_id()
RETURNS TRIGGER AS $$
DECLARE
    seq_num INT;
    prefix TEXT;
BEGIN
    -- If customer_id is already custom provided and valid, keep it
    IF NEW.customer_id IS NOT NULL 
       AND TRIM(NEW.customer_id) != '' 
       AND NEW.customer_id NOT IN ('ADM-01', 'MGR-01', 'RO-01') THEN
        RETURN NEW;
    END IF;

    IF LOWER(NEW.user_type) = 'admin' THEN
        prefix := 'ADM-';
        SELECT COALESCE(MAX(NULLIF(regexp_replace(customer_id, '^ADM-', '', 'i'), '')::INT), 0) + 1
        INTO seq_num
        FROM public.user_auth
        WHERE customer_id ~* '^ADM-[0-9]+$';
        NEW.customer_id := prefix || LPAD(seq_num::TEXT, 2, '0');

    ELSIF LOWER(NEW.user_type) = 'manager' THEN
        prefix := 'MGR-';
        SELECT COALESCE(MAX(NULLIF(regexp_replace(customer_id, '^MGR-', '', 'i'), '')::INT), 0) + 1
        INTO seq_num
        FROM public.user_auth
        WHERE customer_id ~* '^MGR-[0-9]+$';
        NEW.customer_id := prefix || LPAD(seq_num::TEXT, 2, '0');

    ELSIF LOWER(NEW.user_type) = 'ro' THEN
        prefix := 'RO-';
        SELECT COALESCE(MAX(NULLIF(regexp_replace(customer_id, '^RO-', '', 'i'), '')::INT), 0) + 1
        INTO seq_num
        FROM public.user_auth
        WHERE customer_id ~* '^RO-[0-9]+$';
        NEW.customer_id := prefix || LPAD(seq_num::TEXT, 2, '0');
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 5. Attach BEFORE INSERT Trigger
DROP TRIGGER IF EXISTS trg_set_user_auth_customer_id ON public.user_auth;
CREATE TRIGGER trg_set_user_auth_customer_id
BEFORE INSERT ON public.user_auth
FOR EACH ROW
EXECUTE FUNCTION public.set_user_auth_customer_id();

-- 6. High-Performance Indexes
CREATE INDEX IF NOT EXISTS idx_user_auth_mobile_no ON public.user_auth(mobile_no);
CREATE INDEX IF NOT EXISTS idx_user_auth_user_type ON public.user_auth(user_type);
CREATE INDEX IF NOT EXISTS idx_user_auth_customer_id ON public.user_auth(customer_id);
CREATE INDEX IF NOT EXISTS idx_user_auth_pin ON public.user_auth(pin);
CREATE INDEX IF NOT EXISTS idx_user_auth_status ON public.user_auth(status);

-- 7. Grant Permissions to anon, authenticated, and service_role
GRANT ALL ON TABLE public.user_auth TO anon, authenticated, service_role, postgres;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role, postgres;

-- 8. Enable Row Level Security (RLS) & Clean All Existing Policies
ALTER TABLE public.user_auth ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    pol RECORD;
BEGIN
    FOR pol IN (SELECT policyname FROM pg_policies WHERE tablename = 'user_auth' AND schemaname = 'public') LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.user_auth', pol.policyname);
    END LOOP;
END $$;

-- Explicit Granular RLS Policies for full access by anon and authenticated roles
CREATE POLICY "Allow public select user_auth"
ON public.user_auth FOR SELECT
TO anon, authenticated, service_role
USING (true);

CREATE POLICY "Allow public insert user_auth"
ON public.user_auth FOR INSERT
TO anon, authenticated, service_role
WITH CHECK (true);

CREATE POLICY "Allow public update user_auth"
ON public.user_auth FOR UPDATE
TO anon, authenticated, service_role
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow public delete user_auth"
ON public.user_auth FOR DELETE
TO anon, authenticated, service_role
USING (true);

-- ==============================================================================
-- VERIFICATION INSERT EXAMPLE
-- ==============================================================================
-- INSERT INTO public.user_auth (mobile_no, name, pin, user_type)
-- VALUES 
--   ('9876543210', 'First Admin', '123456', 'admin'),
--   ('9876543211', 'Second Admin', '123456', 'admin'),
--   ('9876543212', 'First Manager', '654321', 'manager'),
--   ('9876543213', 'Second Manager', '654321', 'manager');
--
-- Results will be:
-- id: 1, customer_id: 'ADM-01', user_type: 'admin'
-- id: 2, customer_id: 'ADM-02', user_type: 'admin'
-- id: 3, customer_id: 'MGR-01', user_type: 'manager'
-- id: 4, customer_id: 'MGR-02', user_type: 'manager'


