-- ==============================================================================
-- MANGANG FINANCE - DEVICE SESSIONS & MULTI-DEVICE LOCKOUT SCHEMA
-- For LockedDeviceSession Model (lib/models/locked_device_session_model.dart)
-- Execute this script in your Supabase SQL Editor (https://supabase.com/dashboard)
-- ==============================================================================

-- ==============================================================================
-- OPTION 1: DEDICATED TABLE (Recommended Relational Schema)
-- public.device_sessions
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.device_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile_no TEXT NOT NULL,                          -- 10-digit mobile number (e.g. '9876543210')
    user_type TEXT NOT NULL,                          -- 'admin', 'manager', 'ro', 'loanee'
    device_id TEXT NOT NULL,                          -- Hardware UUID / Android device identifier
    user_name TEXT,                                   -- Cached account holder name
    customer_id TEXT,                                 -- Customer ID (e.g. 'ADM-01', 'MGR-01', 'LOAN-102')
    status TEXT NOT NULL DEFAULT 'active',            -- 'active', 'logged_out', 'unblocked'
    is_blocked BOOLEAN NOT NULL DEFAULT true,         -- true = concurrent login on 2nd device blocked
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Composite Unique Constraint:
-- Ensures each mobile number + role combination only has ONE active device session
CREATE UNIQUE INDEX IF NOT EXISTS idx_device_sessions_unique_account 
ON public.device_sessions(mobile_no, user_type);

-- Indexes for lightning fast lookups
CREATE INDEX IF NOT EXISTS idx_device_sessions_lookup 
ON public.device_sessions(mobile_no, user_type, status);

CREATE INDEX IF NOT EXISTS idx_device_sessions_device_id 
ON public.device_sessions(device_id);

CREATE INDEX IF NOT EXISTS idx_device_sessions_customer_id 
ON public.device_sessions(customer_id);

-- Auto-update updated_at timestamp trigger
CREATE OR REPLACE FUNCTION public.update_device_sessions_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_device_sessions_timestamp ON public.device_sessions;
CREATE TRIGGER trg_update_device_sessions_timestamp
BEFORE UPDATE ON public.device_sessions
FOR EACH ROW
EXECUTE FUNCTION public.update_device_sessions_timestamp();

-- Enable Row Level Security (RLS)
ALTER TABLE public.device_sessions ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Public read, insert, and update access (compatible with Supabase anon/authenticated)
DROP POLICY IF EXISTS "Allow all access to device_sessions" ON public.device_sessions;
CREATE POLICY "Allow all access to device_sessions"
ON public.device_sessions FOR ALL
USING (true)
WITH CHECK (true);

-- Enable Realtime for device_sessions table
ALTER PUBLICATION supabase_realtime ADD TABLE public.device_sessions;


-- ==============================================================================
-- OPTION 2: CURRENT REAL-TIME DB SCHEMA (public.system_settings)
-- This is what the Flutter application currently reads and writes to in real-time.
-- Key format: 'active_device_{mobile_no}_{user_type}'
-- Value: hardware device ID (or 'logged_out')
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.system_settings (
    setting_key TEXT PRIMARY KEY,                     -- 'active_device_9876543210_manager'
    setting_value TEXT NOT NULL,                      -- device_id string or 'logged_out'
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for querying active device locks
CREATE INDEX IF NOT EXISTS idx_system_settings_active_devices
ON public.system_settings(setting_key)
WHERE setting_key LIKE 'active_device_%';

-- Auto-update updated_at timestamp trigger for system_settings
CREATE OR REPLACE FUNCTION public.update_system_settings_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_system_settings_timestamp ON public.system_settings;
CREATE TRIGGER trg_update_system_settings_timestamp
BEFORE UPDATE ON public.system_settings
FOR EACH ROW
EXECUTE FUNCTION public.update_system_settings_timestamp();

-- Ensure Row Level Security allows SELECT, INSERT, UPDATE, DELETE for anon role
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access to system_settings" ON public.system_settings;
CREATE POLICY "Allow full access to system_settings"
ON public.system_settings FOR ALL
USING (true)
WITH CHECK (true);

-- Enable Realtime for system_settings table
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
          AND schemaname = 'public' 
          AND tablename = 'system_settings'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.system_settings;
    END IF;
END $$;
